title: ASO by 2Stable
email: support@2stable.com
description: >- # this means to ignore newlines until "baseurl:"
  Easily track and enhance your App Store Optimization strategy, increase downloads and grow your business with our app marketing tool.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

privacy_url: /privacy-policy/
date: "Effective date: December 19, 2020"
terms_of_service_url: /terms-of-service/
roadmap: /roadmap/
support_mail: mailto:support@2stable.com
# github_username: 2stable
twitter_username: aso2stable

main-title: Find the most relevant keywords for your app
main-description: "Easily track and enhance your App Store Optimization strategy, increase downloads and grow your business with our app marketing tool."

app-url: https://apps.apple.com/app/apple-store/id1559277129?pt=122171064&ct=2stable.com.mac&mt=8#?platform=mac
app-src: https://one-badge.com/b/apple/mac.svg
app-alt: macOS Apple App Badge

bootstrap-css: '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">'
bootstrap-icons: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">'
local-css: '<link rel="stylesheet" href="/local.css">'
bootstrap-js-1: '<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>'
bootstrap-js-2: '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>'

analytics: 
  - name: microanalytics
    issuer: '<script data-host="https://microanalytics.io" data-dnt="false" src="https://microanalytics.io/js/script.js" id="ZwSg9rf6GA" async defer></script>'
    include: 1
  - name: splitbee
    issuer: '<script async src="https://cdn.splitbee.io/sb.js"></script>'
    include: 1

footer-c-name: Company
footer-c:
  - name: About
    href: https://2stable.com
  - name: Contact
    href: mailto:support@2stable.com

footer-r-name: Resources
footer-r:
  - name: Roadmap
    href: /roadmap/

footer-d-name: Downloads
footer-d:
  - name: macOS
    href: https://apps.apple.com/app/apple-store/id1559277129?pt=122171064&ct=2stable.com.mac&mt=8#?platform=mac
  - name: iOS
    href: /ios/


# for terms-of-service
APP_NAME: ASO by 2Stable

features:
  - title: No Account Required
    details: All of the data is processed locally on your device.
    image: <i class="bi bi-puzzle"></i>
    # action: Call to action
  - title: Track Visibility in Search
    details: Analyze and compare the visibility in search, either globally or per country.
    image: <i class="bi bi-bullseye"></i>
    # action: Call to action 
  - title: Keyword Research
    details: Choose the most relevant keywords for your app.
    image: <i class="bi bi-search"></i>
    # action: Call to action 
  - title: Top Charts
    details: Browse the top apps for each country and category. Compare top performing apps for Free, Paid and Grossing.
    image: <i class="bi bi-list-ol"></i>
    # action: Call to action 
  - title: Friendly 24/7 Email Support
    details: Our support team is always ready to help you.
    image: <i class="bi bi-life-preserver"></i>
    # action: Call to action 
  - title: Keyword Rankings
    details: Discover what apps are ranking by a specific keyword.
    image: <i class="bi bi-graph-up"></i>
    # action: Call to action 
  - title: and more...
    details: Many other features are on the way.
    image: <i class="bi bi-plus-circle-dotted"></i>
    # action: Call to action 

