title: ASO by 2Stable
email: support@2stable.com
description: >- # this means to ignore newlines until "baseurl:"
  Easily track & optimize your App Store Optimization strategy, increase downloads and grow your business with our app marketing tool.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

privacy_url: /privacy-policy/
date: "Effective date: December 19, 2020"
terms_of_service_url: /terms-of-service/
roadmap: /roadmap/
support_mail: mailto:support@2stable.com
# github_username: 2stable
twitter_username: aso2stable

main-title: ASO Tools to Increase Organic Downloads
main-description: "Easily track & optimize your App Store Optimization strategy, increase downloads and grow your business with our app marketing tool."

app-url: https://apps.apple.com/app/apple-store/id1538761576?pt=122171064&ct=2stable.com.mac&mt=8#?platform=mac
app-src: https://one-badge.com/b/apple/mac.svg
app-alt: macOS Apple App Badge

# for terms-of-service
APP_NAME: ASO by 2Stable

features:
  - title: No Account Required
    details: All the data is processed locally on your device.
    image: <i class="bi bi-puzzle"></i>
    # action: Call to action
  - title: Track Visibility in Search
    details: Analyze and compare the visibility in search per country and globally.
    image: <i class="bi bi-bullseye"></i>
    # action: Call to action 
  - title: Keyword Research
    details: Choose the most relevant keywords for your app.
    image: <i class="bi bi-search"></i>
    # action: Call to action 
  - title: Top Charts
    details: Browse the top apps for each country and category. Compare top performing apps for Free, Paid and Grossing.
    image: <i class="bi bi-list-ol"></i>
    # action: Call to action 
  - title: Friendly 24/7 Email Support
    details: Our support team is always ready to help you.
    image: <i class="bi bi-life-preserver"></i>
    # action: Call to action 
  - title: Keyword Rankings
    details: Discover what apps a ranking by a specific keyword.
    image: <i class="bi bi-graph-up"></i>
    # action: Call to action 
  - title: and more...
    details: Many other features are on the way.
    image: <i class="bi bi-plus-circle-dotted"></i>
    # action: Call to action 

