title: ASO by 2Stable
email: support@2stable.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

privacy_url: /privacy-policy/
date: "Effective date: December 19, 2020"
terms_of_service_url: /terms-of-service/
support_mail: mailto:support@2stable.com
# github_username: 2stable
twitter_username: authwidget

app-url: https://apps.apple.com/app/apple-store/id1538761576?pt=122171064&ct=2stable.com.mac&mt=8#?platform=mac
app-src: https://one-badge.com/b/apple/mac.svg
app-alt: macOS Apple App Badge

# for terms-of-service
APP_NAME: ASO